<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLYfSdEF\Braunstetter_ControlPanel_Test_app_TestKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLYfSdEF/Braunstetter_ControlPanel_Test_app_TestKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLYfSdEF.legacy');

    return;
}

if (!\class_exists(Braunstetter_ControlPanel_Test_app_TestKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLYfSdEF\Braunstetter_ControlPanel_Test_app_TestKernelDevDebugContainer::class, Braunstetter_ControlPanel_Test_app_TestKernelDevDebugContainer::class, false);
}

return new \ContainerLYfSdEF\Braunstetter_ControlPanel_Test_app_TestKernelDevDebugContainer([
    'container.build_hash' => 'LYfSdEF',
    'container.build_id' => '009e4938',
    'container.build_time' => 1630674028,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLYfSdEF');
