<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAKVo8xz\Braunstetter_ControlPanel_Test_app_src_TestKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAKVo8xz/Braunstetter_ControlPanel_Test_app_src_TestKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAKVo8xz.legacy');

    return;
}

if (!\class_exists(Braunstetter_ControlPanel_Test_app_src_TestKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAKVo8xz\Braunstetter_ControlPanel_Test_app_src_TestKernelDevDebugContainer::class, Braunstetter_ControlPanel_Test_app_src_TestKernelDevDebugContainer::class, false);
}

return new \ContainerAKVo8xz\Braunstetter_ControlPanel_Test_app_src_TestKernelDevDebugContainer([
    'container.build_hash' => 'AKVo8xz',
    'container.build_id' => '36f699f5',
    'container.build_time' => 1630679607,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAKVo8xz');
